# link_aliases.s -- AUTO-GENERATED by tools/gen_aliases.py
# ASPSX tail-call aliases resolving name-mangling-mismatch unresolveds.
# Each: the unresolved (caller-side) name tail-jumps to the defined body.
# ABI-correct on MIPS o32 -- args/this already in $a0..$a3 at the call.

	.text
	.align	2
	.set	noreorder
	.set	nomacro

	.globl	AddCarToIngameList__Fe
AddCarToIngameList__Fe:
	j	AddCarToIngameList__11tCarManagerR10tCarModelsRc
	nop

	.globl	AddToPinkSlipsList__Fe
AddToPinkSlipsList__Fe:
	j	AddToPinkSlipsList__11tCarManagersss
	nop

	.globl	AddUpgradesToPinkSlipsList__Fe
AddUpgradesToPinkSlipsList__Fe:
	j	AddUpgradesToPinkSlipsList__11tCarManagersss
	nop

	.globl	AdvanceToNextTrack__Fe
AdvanceToNextTrack__Fe:
	j	AdvanceToNextTrack__18tTournamentManager
	nop

	.globl	AudioCmn_GetAsyncSfx__Fiib
AudioCmn_GetAsyncSfx__Fiib:
	j	AudioCmn_GetAsyncSfx__FiiPv
	nop

	.globl	AudioCmn_LoadFESamples
AudioCmn_LoadFESamples:
	j	AudioCmn_LoadFESamples__Fv
	nop

	.globl	AudioCmn_PlayFESFX__Fe
AudioCmn_PlayFESFX__Fe:
	j	AudioCmn_PlayFESFX__Fi
	nop

	.globl	AudioMus_GetSongList__Fe
AudioMus_GetSongList__Fe:
	j	AudioMus_GetSongList__FPci
	nop

	.globl	AudioMus_PlaySong__Fe
AudioMus_PlaySong__Fe:
	j	AudioMus_PlaySong__FPc
	nop

	.globl	AudioMus_PlaySong__Fie
AudioMus_PlaySong__Fie:
	j	AudioMus_PlaySong__FPc
	nop

	.globl	AudioMus_StopSong__Fe
AudioMus_StopSong__Fe:
	j	AudioMus_StopSong__Fi
	nop

	.globl	AudioMus_StopSong__Fie
AudioMus_StopSong__Fie:
	j	AudioMus_StopSong__Fi
	nop

	.globl	AudioMus_SysCleanUp__Fe
AudioMus_SysCleanUp__Fe:
	j	AudioMus_SysCleanUp__Fv
	nop

	.globl	AudioMus_SysStartUp__Fe
AudioMus_SysStartUp__Fe:
	j	AudioMus_SysStartUp__FiiPc
	nop

	.globl	AudioMus_Threshold__Fie
AudioMus_Threshold__Fie:
	j	AudioMus_Threshold__Fv
	nop

	.globl	AudioMus_Volume__Fe
AudioMus_Volume__Fe:
	j	AudioMus_Volume__Fi
	nop

	.globl	Audio_DeInitDriver
Audio_DeInitDriver:
	j	Audio_DeInitDriver__Fv
	nop

	.globl	Audio_FECleanUp__Fe
Audio_FECleanUp__Fe:
	j	Audio_FECleanUp__Fv
	nop

	.globl	Audio_InitDriver
Audio_InitDriver:
	j	Audio_InitDriver__Fii
	nop

	.globl	Audio_InitDriver__Fe
Audio_InitDriver__Fe:
	j	Audio_InitDriver__Fii
	nop

	.globl	BWAllocMem__Fi
BWAllocMem__Fi:
	j	BWAllocMem__Fl
	nop

	.globl	BWorldSm_TunnelFlagSm__FPv
BWorldSm_TunnelFlagSm__FPv:
	j	BWorldSm_TunnelFlagSm__FP12BWorldSm_Pos
	nop

	.globl	CalcOnOffFade__Fe
CalcOnOffFade__Fe:
	j	CalcOnOffFade__F13tMenuTextTypesssRiT4
	nop

	.globl	CalcTextFadeSelToHi__Fe
CalcTextFadeSelToHi__Fe:
	j	CalcTextFadeSelToHi__F13tMenuTextTypess
	nop

	.globl	CalcTextFadeUnselToSel__Fe
CalcTextFadeUnselToSel__Fe:
	j	CalcTextFadeUnselToSel__F13tMenuTextTypess
	nop

	.globl	CalcTrackFinishDamageBill__Fe
CalcTrackFinishDamageBill__Fe:
	j	CalcTrackFinishDamageBill__18tTournamentManagerbPlT2
	nop

	.globl	CalcUsedPrice__Fe
CalcUsedPrice__Fe:
	j	CalcUsedPrice__11tCarManagers
	nop

	.globl	CarIO_CleanUp
CarIO_CleanUp:
	j	CarIO_CleanUp__Fv
	nop

	.globl	CarIO_CleanUpLicense__Fe
CarIO_CleanUpLicense__Fe:
	j	CarIO_CleanUpLicense__Fi
	nop

	.globl	CarIO_CreateLicense__Fe
CarIO_CreateLicense__Fe:
	j	CarIO_CreateLicense__FPcii
	nop

	.globl	CarIO_ReStart
CarIO_ReStart:
	j	CarIO_ReStart__Fv
	nop

	.globl	CarIO_StartUp
CarIO_StartUp:
	j	CarIO_StartUp__Fv
	nop

	.globl	CheapestCarStockPrice__Fe
CheapestCarStockPrice__Fe:
	j	CheapestCarStockPrice__11tCarManager
	nop

	.globl	CleanupSpinningCarsMenu__Fe
CleanupSpinningCarsMenu__Fe:
	j	CleanupSpinningCarsMenu__Fv
	nop

	.globl	ClearPrimitivesBuffer
ClearPrimitivesBuffer:
	j	ClearPrimitivesBuffer__Fv
	nop

	.globl	Collide_TestWithPlane__FPvP8coorddefT1
Collide_TestWithPlane__FPvP8coorddefT1:
	j	Collide_TestWithPlane__FP13BO_tNewtonObjP8coorddefT1
	nop

	.globl	Controller_SetRamp__Fe
Controller_SetRamp__Fe:
	j	Controller_SetRamp__Fv
	nop

	.globl	CopSpeak_DirectRequest__Fie
CopSpeak_DirectRequest__Fie:
	j	CopSpeak_DirectRequest__FillP8Car_tObjPc
	nop

	.globl	CopSpeak_Flush__Fie
CopSpeak_Flush__Fie:
	j	CopSpeak_Flush__Fv
	nop

	.globl	CopSpeak_GenericBankRequest__Fie
CopSpeak_GenericBankRequest__Fie:
	j	CopSpeak_GenericBankRequest__FiP8Car_tObj
	nop

	.globl	DeInit_Memcard__Fe
DeInit_Memcard__Fe:
	j	DeInit_Memcard__Fv
	nop

	.globl	Debounce__FPv
Debounce__FPv:
	j	Debounce__6tPMenu
	nop

	.globl	Decrement__FPv7tPlayer
Decrement__FPv7tPlayer:
	j	Decrement__13tListIterator7tPlayer
	nop

	.globl	Decrement__Fe
Decrement__Fe:
	j	Decrement__13tListIterator7tPlayer
	nop

	.globl	Display__FPv
Display__FPv:
	j	Display__11tDialogBase
	nop

	.globl	Display__Fe
Display__Fe:
	j	Display__11tDialogBase
	nop

	.globl	DrawC_MenuColorData__Fe
DrawC_MenuColorData__Fe:
	j	DrawC_MenuColorData__FiP8Car_tObji
	nop

	.globl	DrawC_ReadeMapData
DrawC_ReadeMapData:
	j	DrawC_ReadeMapData__Fv
	nop

	.globl	DrawMoney__Fe
DrawMoney__Fe:
	j	DrawMoney__Fiiilii
	nop

	.globl	DrawShapeExtended__Fe
DrawShapeExtended__Fe:
	j	DrawShapeExtended__FiiiiiiP18tDrawShapeExtended
	nop

	.globl	DrawShape_NFS4Rectangle__Fe
DrawShape_NFS4Rectangle__Fe:
	j	DrawShape_NFS4Rectangle__FR4RECT
	nop

	.globl	DrawShape_NFS4RoundRectangle__Fe
DrawShape_NFS4RoundRectangle__Fe:
	j	DrawShape_NFS4RoundRectangle__FiR4RECTs
	nop

	.globl	DrawShape_NFS4RoundRectangle__FiP4RECTs
DrawShape_NFS4RoundRectangle__FiP4RECTs:
	j	DrawShape_NFS4RoundRectangle__FiR4RECTs
	nop

	.globl	DrawShape_NFS4TransRectangle__Fe
DrawShape_NFS4TransRectangle__Fe:
	j	DrawShape_NFS4TransRectangle__FR4RECTs
	nop

	.globl	DrawShape_SubtractNFS4RectEdges__Fe
DrawShape_SubtractNFS4RectEdges__Fe:
	j	DrawShape_SubtractNFS4RectEdges__FR4RECT
	nop

	.globl	DrawSlider__Fe
DrawSlider__Fe:
	j	DrawSlider__FsssssssssbT9ss
	nop

	.globl	DrawTVLines__FP9tTVConfig
DrawTVLines__FP9tTVConfig:
	j	DrawTVLines__FR9tTVConfig
	nop

	.globl	DrawTV__FP9tTVConfig
DrawTV__FP9tTVConfig:
	j	DrawTV__FR9tTVConfig
	nop

	.globl	Draw_DirectSetEnvironment
Draw_DirectSetEnvironment:
	j	Draw_DirectSetEnvironment__Fiiiiiiiiii
	nop

	.globl	Draw_GetDRAWENV__Fe
Draw_GetDRAWENV__Fe:
	j	Draw_GetDRAWENV__Fii
	nop

	.globl	Draw_InitViewOT
Draw_InitViewOT:
	j	Draw_InitViewOT__Fv
	nop

	.globl	Draw_InitViews
Draw_InitViews:
	j	Draw_InitViews__Fv
	nop

	.globl	Draw_MenuRenderingView__Fe
Draw_MenuRenderingView__Fe:
	j	Draw_MenuRenderingView__FP8Car_tObjP13DRender_tViewiiiUliffii
	nop

	.globl	Draw_SetView
Draw_SetView:
	j	Draw_SetView__Fiiiiiiiii
	nop

	.globl	Draw_SetViewMemBudget
Draw_SetViewMemBudget:
	j	Draw_SetViewMemBudget__Fii
	nop

	.globl	FECheat_ActivateBonus__Fi
FECheat_ActivateBonus__Fi:
	j	FECheat_ActivateBonus__F10tCheatCode
	nop

	.globl	FECheat_IsCheatEnabled__Fe
FECheat_IsCheatEnabled__Fe:
	j	FECheat_IsCheatEnabled__F10tCheatCode
	nop

	.globl	FECheat_IsTheUserACryBabyCheater__Fe
FECheat_IsTheUserACryBabyCheater__Fe:
	j	FECheat_IsTheUserACryBabyCheater__Fv
	nop

	.globl	FECheat_LoadBonus__FPUl
FECheat_LoadBonus__FPUl:
	j	FECheat_LoadBonus__FRUl
	nop

	.globl	FECheat_SaveBonus__FPUl
FECheat_SaveBonus__FPUl:
	j	FECheat_SaveBonus__FRUl
	nop

	.globl	FEInput_GetKeyFromPlayer__F7tPlayeri
FEInput_GetKeyFromPlayer__F7tPlayeri:
	j	FEInput_GetKeyFromPlayer__F7tPlayerl
	nop

	.globl	FEInput_GetKeyFromPlayer__Fe
FEInput_GetKeyFromPlayer__Fe:
	j	FEInput_GetKeyFromPlayer__F7tPlayerl
	nop

	.globl	FETextRender_FullTextFade__Fe
FETextRender_FullTextFade__Fe:
	j	FETextRender_FullTextFade__FiPcss13tMenuTextType14tMenuTextStates
	nop

	.globl	FETextRender_FullTextRGB__FPcssici
FETextRender_FullTextRGB__FPcssici:
	j	FETextRender_FullTextRGB__FPcssics
	nop

	.globl	FETextRender_FullTextRGB__Fe
FETextRender_FullTextRGB__Fe:
	j	FETextRender_FullTextRGB__FPcssics
	nop

	.globl	FETextRender_MenuTextPositionedJustifyFade__Fe
FETextRender_MenuTextPositionedJustifyFade__Fe:
	j	FETextRender_MenuTextPositionedJustifyFade__Fissss14tMenuTextState13tMenuTextType
	nop

	.globl	FETextRender_MenuTextPositionedJustifyFade__Fiisss14tMenuTextState13tMenuTextType
FETextRender_MenuTextPositionedJustifyFade__Fiisss14tMenuTextState13tMenuTextType:
	j	FETextRender_MenuTextPositionedJustifyFade__Fissss14tMenuTextState13tMenuTextType
	nop

	.globl	FETextRender_MenuTextPositioned__Fe
FETextRender_MenuTextPositioned__Fe:
	j	FETextRender_MenuTextPositioned__Fsss14tMenuTextState13tMenuTextType
	nop

	.globl	FETextRender_SetABR
FETextRender_SetABR:
	j	FETextRender_SetABR__Fib
	nop

	.globl	FETextRender_WordWrapFade__FisP4RECT14tMenuTextState13tMenuTextType
FETextRender_WordWrapFade__FisP4RECT14tMenuTextState13tMenuTextType:
	j	FETextRender_WordWrapFade__FisR4RECT14tMenuTextState13tMenuTextType
	nop

	.globl	FETextRender_WordWrapHeight__Fe
FETextRender_WordWrapHeight__Fe:
	j	FETextRender_WordWrapHeight__FsPc
	nop

	.globl	FETextRender_WordWrapTextFade__FiPcP4RECT14tMenuTextState13tMenuTextType
FETextRender_WordWrapTextFade__FiPcP4RECT14tMenuTextState13tMenuTextType:
	j	FETextRender_WordWrapTextFade__FiPcR4RECT14tMenuTextState13tMenuTextType
	nop

	.globl	FETextRender_WordWrapTextRGBJustify__FPcP4RECTiiib
FETextRender_WordWrapTextRGBJustify__FPcP4RECTiiib:
	j	FETextRender_WordWrapTextRGBJustify__FPcR4RECTiiib
	nop

	.globl	FETextRender_WordWrapTextRGB__FPcP4RECTi
FETextRender_WordWrapTextRGB__FPcP4RECTi:
	j	FETextRender_WordWrapTextRGB__FPcR4RECTi
	nop

	.globl	FETextRender_WordWrapTextRGB__Fe
FETextRender_WordWrapTextRGB__Fe:
	j	FETextRender_WordWrapTextRGB__FPcR4RECTi
	nop

	.globl	FETextRender_WordWrapText__FPcP4RECT14tMenuTextState13tMenuTextType
FETextRender_WordWrapText__FPcP4RECT14tMenuTextState13tMenuTextType:
	j	FETextRender_WordWrapText__FPcR4RECT14tMenuTextState13tMenuTextType
	nop

	.globl	FETextRender_WordWrap__Fe
FETextRender_WordWrap__Fe:
	j	FETextRender_WordWrap__FsR4RECT14tMenuTextState13tMenuTextType
	nop

	.globl	FETexture_LoadPmx
FETexture_LoadPmx:
	j	FETexture_LoadPmx__FPciP18tTexture_ShapeInfo
	nop

	.globl	Fe3D_InitShowroom
Fe3D_InitShowroom:
	j	Fe3D_InitShowroom__Fv
	nop

	.globl	FeAudio_AsyncPlaySpeech__Fe
FeAudio_AsyncPlaySpeech__Fe:
	j	FeAudio_AsyncPlaySpeech__Fii
	nop

	.globl	FeAudio_DeInitCommentary__Fe
FeAudio_DeInitCommentary__Fe:
	j	FeAudio_DeInitCommentary__Fv
	nop

	.globl	FeAudio_InitCommentary__Fe
FeAudio_InitCommentary__Fe:
	j	FeAudio_InitCommentary__Fii
	nop

	.globl	FeTools_deinit__Fe
FeTools_deinit__Fe:
	j	FeTools_deinit__Fv
	nop

	.globl	FeTools_init
FeTools_init:
	j	FeTools_init__Fv
	nop

	.globl	FeignAlloc__FPvi
FeignAlloc__FPvi:
	j	FeignAlloc__FP9SimpleMemi
	nop

	.globl	FindSimilarCar__Fe
FindSimilarCar__Fe:
	j	FindSimilarCar__11tCarManagerR10tCarModelsRcsP10tCarModels
	nop

	.globl	Flare_CarShapedHalo__FiP7COORD16iisiP15Draw_FlareCache
Flare_CarShapedHalo__FiP7COORD16iisiP15Draw_FlareCache:
	j	Flare_CarShapedHalo__FiP7COORD16N21siP15Draw_FlareCache
	nop

	.globl	FontUpsideDownBlit__Fe
FontUpsideDownBlit__Fe:
	j	FontUpsideDownBlit__FiiPviiP12charactertbli
	nop

	.globl	Font_GetUVWH__FiPvN41
Font_GetUVWH__FiPvN41:
	j	Font_GetUVWH__FcPiN41
	nop

	.globl	Font_LoadFont__FPciii
Font_LoadFont__FPciii:
	j	Font_LoadFont__FPciic
	nop

	.globl	Font_SetBlitter__Fe
Font_SetBlitter__Fe:
	j	Font_SetBlitter__FPFiiPviiP12charactertbli_v
	nop

	.globl	Front_GetTrackRaced__Fe
Front_GetTrackRaced__Fe:
	j	Front_GetTrackRaced__Fv
	nop

	.globl	Front_InitialMemCardCheck
Front_InitialMemCardCheck:
	j	Front_InitialMemCardCheck__Fv
	nop

	.globl	Front_ResetPSXController__FiUi
Front_ResetPSXController__FiUi:
	j	Front_ResetPSXController__Fii
	nop

	.globl	Front_SecondaryMemCardCheck
Front_SecondaryMemCardCheck:
	j	Front_SecondaryMemCardCheck__Fv
	nop

	.globl	GetAwardInformation__Fe
GetAwardInformation__Fe:
	j	GetAwardInformation__18tTournamentManagerP17tAwardInformation
	nop

	.globl	GetCarFromID__Fe
GetCarFromID__Fe:
	j	GetCarFromID__11tCarManagers
	nop

	.globl	GetClassList__Fe
GetClassList__Fe:
	j	GetClassList__11tCarManager13tCarClassTypesP10tCarModels
	nop

	.globl	GetGarageCar__FP11tCarManagerUsP8tCarInfoi
GetGarageCar__FP11tCarManagerUsP8tCarInfoi:
	j	GetGarageCar__11tCarManagersR8tCarInfos
	nop

	.globl	GetGarageCar__Fe
GetGarageCar__Fe:
	j	GetGarageCar__11tCarManagersR8tCarInfos
	nop

	.globl	GetLastTrackRaced__Fe
GetLastTrackRaced__Fe:
	j	GetLastTrackRaced__18tTournamentManager
	nop

	.globl	GetMissionStages__Fe
GetMissionStages__Fe:
	j	GetMissionStages__15tMissionManagerssPP10tStageInfo
	nop

	.globl	GetMissionToRace__Fe
GetMissionToRace__Fe:
	j	GetMissionToRace__15tMissionManagerPP12tMissionInfo
	nop

	.globl	GetNumOwnedCars__Fe
GetNumOwnedCars__Fe:
	j	GetNumOwnedCars__11tCarManagers
	nop

	.globl	GetNumPinkSlipsCars__Fe
GetNumPinkSlipsCars__Fe:
	j	GetNumPinkSlipsCars__11tCarManagers
	nop

	.globl	GetNumTourneyCars__Fe
GetNumTourneyCars__Fe:
	j	GetNumTourneyCars__11tCarManagers
	nop

	.globl	GetPinkSlipsCar__Fe
GetPinkSlipsCar__Fe:
	j	GetPinkSlipsCar__11tCarManagersR8tCarInfos
	nop

	.globl	GetStockCar__Fe
GetStockCar__Fe:
	j	GetStockCar__11tCarManagersR8tCarInfo
	nop

	.globl	GetTrackByID__Fe
GetTrackByID__Fe:
	j	GetTrackByID__13tTrackManagers
	nop

	.globl	GetTrackToRace__FP18tTournamentManagerPv
GetTrackToRace__FP18tTournamentManagerPv:
	j	GetTrackToRace__18tTournamentManagerP10tTrackInfo
	nop

	.globl	GetTrackToRace__Fe
GetTrackToRace__Fe:
	j	GetTrackToRace__18tTournamentManagerP10tTrackInfo
	nop

	.globl	GetTrack__FP13tTrackManagerUsPv
GetTrack__FP13tTrackManagerUsPv:
	j	GetTrack__FP13tTrackManagerUiPv
	nop

	.globl	GetTrack__Fe
GetTrack__Fe:
	j	GetTrack__FP13tTrackManagerUiPv
	nop

	.globl	GetTrophyName__FP18tTournamentManagerP12tTourneyInfo11tTrophySizePci
GetTrophyName__FP18tTournamentManagerP12tTourneyInfo11tTrophySizePci:
	j	GetTrophyName__18tTournamentManagerP12tTourneyInfo11tTrophySizePci
	nop

	.globl	Hide__FPv
Hide__FPv:
	j	Hide__11tDialogBase
	nop

	.globl	Hide__Fe
Hide__Fe:
	j	Hide__11tDialogBase
	nop

	.globl	Hud_BTCStats__Fsc
Hud_BTCStats__Fsc:
	j	Hud_BTCStats__Fsi
	nop

	.globl	Hud_BuildString__FPciiiii
Hud_BuildString__FPciiiii:
	j	Hud_BuildString__FPciiiib
	nop

	.globl	InGame_ResetPSXController__FUii
InGame_ResetPSXController__FUii:
	j	InGame_ResetPSXController__Fii
	nop

	.globl	Increment__FPv7tPlayer
Increment__FPv7tPlayer:
	j	Increment__13tListIterator7tPlayer
	nop

	.globl	Increment__Fe
Increment__Fe:
	j	Increment__13tListIterator7tPlayer
	nop

	.globl	InitTV__FP9tTVConfigP18tTexture_ShapeInfos
InitTV__FP9tTVConfigP18tTexture_ShapeInfos:
	j	InitTV__FR9tTVConfigP18tTexture_ShapeInfos
	nop

	.globl	Init_Memcard__FbUc
Init_Memcard__FbUc:
	j	Init_Memcard__FbT0
	nop

	.globl	Init_Memcard__Fe
Init_Memcard__Fe:
	j	Init_Memcard__FbT0
	nop

	.globl	Init_PSX_FrontEnd__Fe
Init_PSX_FrontEnd__Fe:
	j	Init_PSX_FrontEnd__Fv
	nop

	.globl	InitializeIngameCarList__Fe
InitializeIngameCarList__Fe:
	j	InitializeIngameCarList__11tCarManager
	nop

	.globl	InitializeSpinningCars__Fe
InitializeSpinningCars__Fe:
	j	InitializeSpinningCars__Fv
	nop

	.globl	Initialize__FP10tVideoWallP9tTVConfigP18tTexture_ShapeInfossPss
Initialize__FP10tVideoWallP9tTVConfigP18tTexture_ShapeInfossPss:
	j	Initialize__5tMenu
	nop

	.globl	Input_Interface__Fii
Input_Interface__Fii:
	j	Input_Interface__FUli
	nop

	.globl	IsCarAnAddedModel__Fe
IsCarAnAddedModel__Fe:
	j	IsCarAnAddedModel__11tCarManagerR10tCarModelsRc
	nop

	.globl	IsDisabled__Fi
IsDisabled__Fi:
	j	IsDisabled__10tPMenuItem
	nop

	.globl	IsEnabled__Fi
IsEnabled__Fi:
	j	IsEnabled__10tPMenuItem
	nop

	.globl	IsTournamentFinished__Fe
IsTournamentFinished__Fe:
	j	IsTournamentFinished__18tTournamentManager
	nop

	.globl	ItemEnabledNum__FPvi
ItemEnabledNum__FPvi:
	j	ItemEnabledNum__6tPMenui
	nop

	.globl	LoadDescription__Fe
LoadDescription__Fe:
	j	LoadDescription__11tCarManager
	nop

	.globl	LoadGame__Fe
LoadGame__Fe:
	j	LoadGame__FsbUc
	nop

	.globl	MCRD_fileexists__FiPc
MCRD_fileexists__FiPc:
	j	MCRD_fileexists
	nop

	.globl	MCRD_getcard
MCRD_getcard:
	j	MCRD_getcard__Fi
	nop

	.globl	MCRD_getcard__Fe
MCRD_getcard__Fe:
	j	MCRD_getcard__Fi
	nop

	.globl	MCRD_getopts__FP12MCRDOPTS_def
MCRD_getopts__FP12MCRDOPTS_def:
	j	MCRD_getopts
	nop

	.globl	MCRD_handlecardevents__Fe
MCRD_handlecardevents__Fe:
	j	MCRD_handlecardevents
	nop

	.globl	MCRD_handlecardevents__Fi
MCRD_handlecardevents__Fi:
	j	MCRD_handlecardevents
	nop

	.globl	MCRD_init__Fi
MCRD_init__Fi:
	j	MCRD_init
	nop

	.globl	MCRD_loadfile__FiP12MCRDFILE_defi
MCRD_loadfile__FiP12MCRDFILE_defi:
	j	MCRD_loadfile
	nop

	.globl	MCRD_restore__Fv
MCRD_restore__Fv:
	j	MCRD_restore
	nop

	.globl	MCRD_savefile__FiP12MCRDFILE_def
MCRD_savefile__FiP12MCRDFILE_def:
	j	MCRD_savefile
	nop

	.globl	MCRD_setopts__FP12MCRDOPTS_def
MCRD_setopts__FP12MCRDOPTS_def:
	j	MCRD_setopts
	nop

	.globl	MenuExtended_PostGameMenu__FR12tMenuCommand
MenuExtended_PostGameMenu__FR12tMenuCommand:
	j	MenuExtended_PostGameMenu__FP12tMenuCommand
	nop

	.globl	MenuExtended_TransitionFromPostGameToMainMenu__Fe
MenuExtended_TransitionFromPostGameToMainMenu__Fe:
	j	MenuExtended_TransitionFromPostGameToMainMenu__FP12tMenuCommand
	nop

	.globl	MenuNFS4_SetHelpPos__Fe
MenuNFS4_SetHelpPos__Fe:
	j	MenuNFS4_SetHelpPos__FP4RECT
	nop

	.globl	Newton_CalcRealShadowCoordinates__FP8Car_tObji
Newton_CalcRealShadowCoordinates__FP8Car_tObji:
	j	Newton_CalcRealShadowCoordinates__Fii
	nop

	.globl	Newton_DoPostBarrierCollisionHandling__FP13BO_tNewtonObjG8coorddef
Newton_DoPostBarrierCollisionHandling__FP13BO_tNewtonObjG8coorddef:
	j	Newton_DoPostBarrierCollisionHandling__FP8Car_tObjG8coorddef
	nop

	.globl	NumEnabledItems__FPv
NumEnabledItems__FPv:
	j	NumEnabledItems__6tPMenu
	nop

	.globl	PAD_state
PAD_state:
	j	PAD_state__Fi
	nop

	.globl	PSXDrawBrightEndLine__Fe
PSXDrawBrightEndLine__Fe:
	j	PSXDrawBrightEndLine__Fiiiiiiii
	nop

	.globl	PSXExitFrontend__Fe
PSXExitFrontend__Fe:
	j	PSXExitFrontend__Fv
	nop

	.globl	Platform_GetDCTBuffer__Fe
Platform_GetDCTBuffer__Fe:
	j	Platform_GetDCTBuffer__FiPc
	nop

	.globl	Platform_ResetDCTBuffer
Platform_ResetDCTBuffer:
	j	Platform_ResetDCTBuffer__Fv
	nop

	.globl	Platform_ResetDCTBuffer__Fe
Platform_ResetDCTBuffer__Fe:
	j	Platform_ResetDCTBuffer__Fv
	nop

	.globl	PlayerName__Fe
PlayerName__Fe:
	j	PlayerName__Fi
	nop

	.globl	PlayerRanking__Fe
PlayerRanking__Fe:
	j	PlayerRanking__18tTournamentManagers
	nop

	.globl	PurchaseCar__Fe
PurchaseCar__Fe:
	j	PurchaseCar__11tCarManagersss
	nop

	.globl	PurchaseUpgrade__Fe
PurchaseUpgrade__Fe:
	j	PurchaseUpgrade__11tCarManagersss
	nop

	.globl	R3DCar_CleanUp
R3DCar_CleanUp:
	j	R3DCar_CleanUp__Fv
	nop

	.globl	R3DCar_DeInstantiate3DCar
R3DCar_DeInstantiate3DCar:
	j	R3DCar_DeInstantiate3DCar__FP8Car_tObj
	nop

	.globl	R3DCar_DeInstantiate3DCarMenu
R3DCar_DeInstantiate3DCarMenu:
	j	R3DCar_DeInstantiate3DCarMenu__FP8Car_tObj
	nop

	.globl	R3DCar_InsertCarFacetMenu__FP8Car_tObji
R3DCar_InsertCarFacetMenu__FP8Car_tObji:
	j	R3DCar_InsertCarFacetMenu__FP8Car_tObjP13DRender_tView
	nop

	.globl	R3DCar_Instantiate3DCar
R3DCar_Instantiate3DCar:
	j	R3DCar_Instantiate3DCar__FP8Car_tObji
	nop

	.globl	R3DCar_PostStartUp
R3DCar_PostStartUp:
	j	R3DCar_PostStartUp__Fv
	nop

	.globl	R3DCar_StartUp
R3DCar_StartUp:
	j	R3DCar_StartUp__Fv
	nop

	.globl	Redraw__FPv
Redraw__FPv:
	j	Redraw__14tFEApplication
	nop

	.globl	Redraw__Fe
Redraw__Fe:
	j	Redraw__14tFEApplication
	nop

	.globl	RunFrontEnd__Fe
RunFrontEnd__Fe:
	j	RunFrontEnd__14tFEApplication
	nop

	.globl	RunPostGame__Fe
RunPostGame__Fe:
	j	RunPostGame__14tFEApplication
	nop

	.globl	Run__Fe
Run__Fe:
	j	Run__18tDialogInteractive
	nop

	.globl	SaveGame__Fe
SaveGame__Fe:
	j	SaveGame__Fs
	nop

	.globl	SavePinkSlipsCarsWithErrorDialogs__Fe
SavePinkSlipsCarsWithErrorDialogs__Fe:
	j	SavePinkSlipsCarsWithErrorDialogs__Fsss
	nop

	.globl	SavePinkSlipsCars__FP11tCarManagerP12tSaveCarInfos
SavePinkSlipsCars__FP11tCarManagerP12tSaveCarInfos:
	j	SavePinkSlipsCars__Fss
	nop

	.globl	Sched_ExecuteCheck__FiiiiPiT4Pci
Sched_ExecuteCheck__FiiiiPiT4Pci:
	j	Sched_ExecuteCheck__FiiiiPiN24i
	nop

	.globl	SellCar__Fe
SellCar__Fe:
	j	SellCar__11tCarManagerss
	nop

	.globl	SetAvailableIcon__FP10tVideoWallssssP18tTexture_ShapeInfo
SetAvailableIcon__FP10tVideoWallssssP18tTexture_ShapeInfo:
	j	SetAvailableIcon__10tVideoWallssssP18tTexture_ShapeInfo
	nop

	.globl	SetAvailableIcon__Fe
SetAvailableIcon__Fe:
	j	SetAvailableIcon__10tVideoWallssssP18tTexture_ShapeInfo
	nop

	.globl	SetCarAvailable__Fe
SetCarAvailable__Fe:
	j	SetCarAvailable__11tCarManager10tCarModelsb
	nop

	.globl	SetCarViewable__Fe
SetCarViewable__Fe:
	j	SetCarViewable__11tCarManager10tCarModelsb
	nop

	.globl	SetClassAvailable__Fe
SetClassAvailable__Fe:
	j	SetClassAvailable__11tCarManager13tCarClassTypeb
	nop

	.globl	SetDimensions__Fe
SetDimensions__Fe:
	j	SetDimensions__24tMenuItemLeftRightSliderssss
	nop

	.globl	SetLicensePlate__Fe
SetLicensePlate__Fe:
	j	SetLicensePlate__Fv
	nop

	.globl	SetMenu__FP20tMenuItemSlidingMenusPv
SetMenu__FP20tMenuItemSlidingMenusPv:
	j	SetMenu__14tFEApplicationsP5tMenu
	nop

	.globl	SetOffset__Fe
SetOffset__Fe:
	j	SetOffset__10tVideoWallss
	nop

	.globl	SetPlayList
SetPlayList:
	j	SetPlayList__Fi
	nop

	.globl	SetState__Fe
SetState__Fe:
	j	SetState__16tScreenCarSelecti
	nop

	.globl	SetTrackAvailable__Fe
SetTrackAvailable__Fe:
	j	SetTrackAvailable__13tTrackManagersb
	nop

	.globl	SetValid__Fe
SetValid__Fe:
	j	SetValid__10tVideoWalls
	nop

	.globl	Setup__Fe
Setup__Fe:
	j	Setup__14AIDataRecord_t
	nop

	.globl	Speech_ct__FP6Speech
Speech_ct__FP6Speech:
	j	Speech_ct__FPUi
	nop

	.globl	Speech_dt__FP6Speechi
Speech_dt__FP6Speechi:
	j	Speech_dt__FPvUi
	nop

	.globl	StartNewTournament__Fe
StartNewTournament__Fe:
	j	StartNewTournament__18tTournamentManagerUcUc
	nop

	.globl	StatChk_ClearNewRecords__Fe
StatChk_ClearNewRecords__Fe:
	j	StatChk_ClearNewRecords__Fv
	nop

	.globl	StatChk_IsRecordLapTime__Fe
StatChk_IsRecordLapTime__Fe:
	j	StatChk_IsRecordLapTime__FP10Car_tStatssPs
	nop

	.globl	StatChk_IsTopTime__Fe
StatChk_IsTopTime__Fe:
	j	StatChk_IsTopTime__FP10Car_tStatss
	nop

	.globl	StatChk_SaveRecordLapTime__Fe
StatChk_SaveRecordLapTime__Fe:
	j	StatChk_SaveRecordLapTime__FP10Car_tStatsss
	nop

	.globl	StatChk_SaveTopTime__Fe
StatChk_SaveTopTime__Fe:
	j	StatChk_SaveTopTime__FP10Car_tStatss
	nop

	.globl	StatTool_UpperCaseItKeepingInMindThoseBloodySpecialCharacters__Fe
StatTool_UpperCaseItKeepingInMindThoseBloodySpecialCharacters__Fe:
	j	StatTool_UpperCaseItKeepingInMindThoseBloodySpecialCharacters__FPc
	nop

	.globl	Stattool_GetAINameFromPersonality__Fe
Stattool_GetAINameFromPersonality__Fe:
	j	Stattool_GetAINameFromPersonality__F14tPersonalities
	nop

	.globl	Stattool_GetAllDefaultRecords__Fe
Stattool_GetAllDefaultRecords__Fe:
	j	Stattool_GetAllDefaultRecords__FP13tRecordBufferb
	nop

	.globl	Stattool_ReturnRecordLapTime__Fe
Stattool_ReturnRecordLapTime__Fe:
	j	Stattool_ReturnRecordLapTime__Fs
	nop

	.globl	SwapBackground__Fe
SwapBackground__Fe:
	j	SwapBackground__11tScreenMaini
	nop

	.globl	TextSys_LoadWords
TextSys_LoadWords:
	j	TextSys_LoadWords__Fi
	nop

	.globl	TextSys_UnloadWords__Fe
TextSys_UnloadWords__Fe:
	j	TextSys_UnloadWords__Fv
	nop

	.globl	TextSys_Word__Fe
TextSys_Word__Fe:
	j	TextSys_Word__Fi
	nop

	.globl	TextValue__FPv7tPlayer
TextValue__FPv7tPlayer:
	j	TextValue__13tListIterator7tPlayer
	nop

	.globl	Texture_CleanupMenuTexture
Texture_CleanupMenuTexture:
	j	Texture_CleanupMenuTexture__Fv
	nop

	.globl	Texture_GetClutId
Texture_GetClutId:
	j	Texture_GetClutId__FiPiT1
	nop

	.globl	Texture_InitMenuClut
Texture_InitMenuClut:
	j	Texture_InitMenuClut__Fv
	nop

	.globl	Texture_InitMenuTexture
Texture_InitMenuTexture:
	j	Texture_InitMenuTexture__Fv
	nop

	.globl	Texture_KillMenuTexture
Texture_KillMenuTexture:
	j	Texture_KillMenuTexture__Fv
	nop

	.globl	TournPointTotal__Fe
TournPointTotal__Fe:
	j	TournPointTotal__18tTournamentManagerPs
	nop

	.globl	TransitionOff__Fe
TransitionOff__Fe:
	j	TransitionOff__5tMenu
	nop

	.globl	TransitionOn__Fe
TransitionOn__Fe:
	j	TransitionOn__5tMenu
	nop

	.globl	TurnOffTV__FP9tTVConfig
TurnOffTV__FP9tTVConfig:
	j	TurnOffTV__FR9tTVConfig
	nop

	.globl	TurnOnTV__FP9tTVConfig
TurnOnTV__FP9tTVConfig:
	j	TurnOnTV__FR9tTVConfig
	nop

	.globl	UpdateAwardInformation__Fe
UpdateAwardInformation__Fe:
	j	UpdateAwardInformation__18tTournamentManager
	nop

	.globl	UpdateCarLineup__Fe
UpdateCarLineup__Fe:
	j	UpdateCarLineup__18tTournamentManager
	nop

	.globl	UploadShapes__Fe
UploadShapes__Fe:
	j	UploadShapes__7tScreenR17tShapeInformationssss
	nop

	.globl	UploadSwapShapes__Fe
UploadSwapShapes__Fe:
	j	UploadSwapShapes__7tScreeni
	nop

	.globl	_._31tDialogMessageStringWithTimeout
_._31tDialogMessageStringWithTimeout:
	j	_._20tDialogMessageString
	nop

	.globl	garyMemCardGrabBlocks__Fii
garyMemCardGrabBlocks__Fii:
	j	garyMemCardGrabBlocks
	nop

	.globl	inittextdraw
inittextdraw:
	j	inittextdraw__Fv
	nop

	.globl	mdecreset
mdecreset:
	j	mdecreset__Fv
	nop

	.globl	play_movie
play_movie:
	j	play_movie__Fc
	nop

	.globl	play_movie__Fi
play_movie__Fi:
	j	play_movie__Fc
	nop

	.globl	s_lower__Fe
s_lower__Fe:
	j	s_lower__FPc
	nop

	.globl	systemtask__Fi
systemtask__Fi:
	j	systemtask
	nop

	.globl	tAllScreens_ctor__Fe
tAllScreens_ctor__Fe:
	j	__11tAllScreens
	nop

	.globl	tAllScreens_dtor__Fe
tAllScreens_dtor__Fe:
	j	_._11tAllScreens
	nop

	.globl	tDialogYesNo_ctor__Fe
tDialogYesNo_ctor__Fe:
	j	tDialogYesNo_ctor__FP12tDialogYesNo
	nop

	.globl	tFEApplication_ctor__Fe
tFEApplication_ctor__Fe:
	j	__14tFEApplication
	nop

	.globl	tFEApplication_dtor__Fe
tFEApplication_dtor__Fe:
	j	_._14tFEApplication
	nop

	.globl	tGlobalMenuDefs_ctor__Fe
tGlobalMenuDefs_ctor__Fe:
	j	__15tGlobalMenuDefs
	nop

	.globl	tGlobalMenuDefs_dtor__Fe
tGlobalMenuDefs_dtor__Fe:
	j	_._15tGlobalMenuDefs
	nop

	.globl	tInsideBoxLeftRightSlider_ctor__Fe
tInsideBoxLeftRightSlider_ctor__Fe:
	j	__25tInsideBoxLeftRightSliderUiP13tListIterator
	nop

	.globl	tInsideBoxLeftRightSlider_dtor__Fe
tInsideBoxLeftRightSlider_dtor__Fe:
	j	_._25tInsideBoxLeftRightSlider
	nop

	.globl	tInsideBoxMenu_ctor__Fe
tInsideBoxMenu_ctor__Fe:
	j	__14tInsideBoxMenuUiP7tScreenP5tMenuT3PFR12tMenuCommand_vsP9tMenuIteme
	nop

	.globl	tInsideBoxMenu_dtor__Fe
tInsideBoxMenu_dtor__Fe:
	j	_._14tInsideBoxMenu
	nop

	.globl	tInsideBoxSongMenu_ctor__Fe
tInsideBoxSongMenu_ctor__Fe:
	j	__18tInsideBoxSongMenuUiP7tScreenP5tMenuT3PFR12tMenuCommand_vsP9tMenuIteme
	nop

	.globl	tInsideBoxSongMenu_dtor__Fe
tInsideBoxSongMenu_dtor__Fe:
	j	_._18tInsideBoxSongMenu
	nop

	.globl	tInsideBoxTwoWaySlider_ctor__Fe
tInsideBoxTwoWaySlider_ctor__Fe:
	j	__22tInsideBoxTwoWaySliderUiP13tListIteratori
	nop

	.globl	tInsideBoxTwoWaySlider_dtor__Fe
tInsideBoxTwoWaySlider_dtor__Fe:
	j	_._22tInsideBoxTwoWaySlider
	nop

	.globl	tListIteratorCarColor_ctor__Fe
tListIteratorCarColor_ctor__Fe:
	j	__21tListIteratorCarColorPcN21iP11tCarManager
	nop

	.globl	tListIteratorCarColor_dtor__Fe
tListIteratorCarColor_dtor__Fe:
	j	_._21tListIteratorCarColor
	nop

	.globl	tListIteratorCar_ctor__Fe
tListIteratorCar_ctor__Fe:
	j	__16tListIteratorCarPcP11tCarManager
	nop

	.globl	tListIteratorCar_dtor__Fe
tListIteratorCar_dtor__Fe:
	j	_._16tListIteratorCar
	nop

	.globl	tListIteratorIndexed_ctor__Fe
tListIteratorIndexed_ctor__Fe:
	j	__20tListIteratorIndexedPsPcT2
	nop

	.globl	tListIteratorIndexed_dtor__Fe
tListIteratorIndexed_dtor__Fe:
	j	_._20tListIteratorIndexed
	nop

	.globl	tListIteratorRangeIndexed_ctor__Fe
tListIteratorRangeIndexed_ctor__Fe:
	j	__25tListIteratorRangeIndexedccPcT3
	nop

	.globl	tListIteratorRangeIndexed_dtor__Fe
tListIteratorRangeIndexed_dtor__Fe:
	j	_._25tListIteratorRangeIndexed
	nop

	.globl	tListIteratorRange_ctor__Fe
tListIteratorRange_ctor__Fe:
	j	__18tListIteratorRangeccPc
	nop

	.globl	tListIteratorRange_dtor__Fe
tListIteratorRange_dtor__Fe:
	j	_._18tListIteratorRange
	nop

	.globl	tListIteratorTournament_ctor__Fe
tListIteratorTournament_ctor__Fe:
	j	__23tListIteratorTournamentPcP18tTournamentManager
	nop

	.globl	tListIteratorTournament_dtor__Fe
tListIteratorTournament_dtor__Fe:
	j	_._23tListIteratorTournament
	nop

	.globl	tListIteratorTrack_ctor__Fe
tListIteratorTrack_ctor__Fe:
	j	__18tListIteratorTrackPcT1P13tTrackManager
	nop

	.globl	tListIteratorTrack_dtor__Fe
tListIteratorTrack_dtor__Fe:
	j	_._18tListIteratorTrack
	nop

	.globl	tListIterator_ctor__FP13tListIteratorPsPc
tListIterator_ctor__FP13tListIteratorPsPc:
	j	__13tListIteratorPsPc
	nop

	.globl	tListIterator_ctor__Fe
tListIterator_ctor__Fe:
	j	__13tListIteratorPsPc
	nop

	.globl	tListIterator_dtor__Fe
tListIterator_dtor__Fe:
	j	tListIterator_dtor__FP13tListIterator
	nop

	.globl	tMenuBlank_ctor__Fe
tMenuBlank_ctor__Fe:
	j	__10tMenuBlankUiP7tScreenP5tMenuT3PFR12tMenuCommand_vs
	nop

	.globl	tMenuBlank_dtor__Fe
tMenuBlank_dtor__Fe:
	j	_._10tMenuBlank
	nop

	.globl	tMenuItemGoToMenuButton_ctor__Fe
tMenuItemGoToMenuButton_ctor__Fe:
	j	__23tMenuItemGoToMenuButtonUiP5tMenuPFR12tMenuCommand_v
	nop

	.globl	tMenuItemGoToMenuButton_dtor__Fe
tMenuItemGoToMenuButton_dtor__Fe:
	j	_._23tMenuItemGoToMenuButton
	nop

	.globl	tMenuItemGoToMenuNFS4Button_ctor__Fe
tMenuItemGoToMenuNFS4Button_ctor__Fe:
	j	__27tMenuItemGoToMenuNFS4ButtonUiP5tMenuPFR12tMenuCommand_vii
	nop

	.globl	tMenuItemGoToMenuNFS4Button_dtor__Fe
tMenuItemGoToMenuNFS4Button_dtor__Fe:
	j	_._27tMenuItemGoToMenuNFS4Button
	nop

	.globl	tMenuItemLeftRightAudioSlider_ctor__Fe
tMenuItemLeftRightAudioSlider_ctor__Fe:
	j	__29tMenuItemLeftRightAudioSliderUiP13tListIteratori
	nop

	.globl	tMenuItemLeftRightAudioSlider_dtor__Fe
tMenuItemLeftRightAudioSlider_dtor__Fe:
	j	_._29tMenuItemLeftRightAudioSlider
	nop

	.globl	tMenuItemLeftRightChoice_ctor__Fe
tMenuItemLeftRightChoice_ctor__Fe:
	j	__24tMenuItemLeftRightChoiceUiP13tListIterator
	nop

	.globl	tMenuItemLeftRightChoice_dtor__Fe
tMenuItemLeftRightChoice_dtor__Fe:
	j	_._24tMenuItemLeftRightChoice
	nop

	.globl	tMenuItemLeftRightFade_ctor__Fe
tMenuItemLeftRightFade_ctor__Fe:
	j	__22tMenuItemLeftRightFadeUiP13tListIterator
	nop

	.globl	tMenuItemNFS4LeftRightChoice_ctor__Fe
tMenuItemNFS4LeftRightChoice_ctor__Fe:
	j	__28tMenuItemNFS4LeftRightChoiceUiP13tListIteratorii
	nop

	.globl	tMenuItemNFS4LeftRightChoice_dtor__Fe
tMenuItemNFS4LeftRightChoice_dtor__Fe:
	j	_._28tMenuItemNFS4LeftRightChoice
	nop

	.globl	tMenuItemSlidingMenu_ctor__Fe
tMenuItemSlidingMenu_ctor__Fe:
	j	__20tMenuItemSlidingMenuUissssb
	nop

	.globl	tMenuItemSlidingMenu_dtor__Fe
tMenuItemSlidingMenu_dtor__Fe:
	j	_._20tMenuItemSlidingMenu
	nop

	.globl	tMenuItem_dtor__Fe
tMenuItem_dtor__Fe:
	j	_._9tMenuItem
	nop

	.globl	tMenuNFS4Bottom_ctor__Fe
tMenuNFS4Bottom_ctor__Fe:
	j	__15tMenuNFS4BottomUiP7tScreenP5tMenuT3PFR12tMenuCommand_vsP9tMenuIteme
	nop

	.globl	tMenuNFS4Bottom_dtor__Fe
tMenuNFS4Bottom_dtor__Fe:
	j	_._15tMenuNFS4Bottom
	nop

	.globl	tMenuNFS4TwoPlayer_ctor__Fe
tMenuNFS4TwoPlayer_ctor__Fe:
	j	__18tMenuNFS4TwoPlayerUiP7tScreenP5tMenuT3PFR12tMenuCommand_vsP9tMenuIteme
	nop

	.globl	tMenuNFS4TwoPlayer_dtor__Fe
tMenuNFS4TwoPlayer_dtor__Fe:
	j	_._18tMenuNFS4TwoPlayer
	nop

	.globl	tMenuNFS4_ctor__Fe
tMenuNFS4_ctor__Fe:
	j	__9tMenuNFS4UiP7tScreenP5tMenuT3PFR12tMenuCommand_vs
	nop

	.globl	tMenuNFS4_dtor__Fe
tMenuNFS4_dtor__Fe:
	j	_._9tMenuNFS4
	nop

	.globl	tMenuOptions_ctor__Fe
tMenuOptions_ctor__Fe:
	j	__12tMenuOptionsUiP7tScreenP5tMenuT3PFR12tMenuCommand_vssP9tMenuIteme
	nop

	.globl	tMenuOptions_dtor__Fe
tMenuOptions_dtor__Fe:
	j	_._12tMenuOptions
	nop

	.globl	tOptionsMenu_ctor__Fe
tOptionsMenu_ctor__Fe:
	j	__12tOptionsMenuUiP7tScreenP5tMenuT3PFR12tMenuCommand_vsiiP9tMenuIteme
	nop

	.globl	tOptionsMenu_dtor__Fe
tOptionsMenu_dtor__Fe:
	j	_._12tOptionsMenu
	nop

	.globl	tPListIteratorIndexed_ct__Fie
tPListIteratorIndexed_ct__Fie:
	j	__21tPListIteratorIndexedPsPiPc
	nop

	.globl	tPListIteratorIndexed_dt__FPvi
tPListIteratorIndexed_dt__FPvi:
	j	_._21tPListIteratorIndexed
	nop

	.globl	tPListIterator_ct__Fie
tPListIterator_ct__Fie:
	j	__14tPListIteratorPsPi
	nop

	.globl	tPListIterator_dt__FPvi
tPListIterator_dt__FPvi:
	j	_._14tPListIterator
	nop

	.globl	tPMenuItemCommandButton_ct__Fie
tPMenuItemCommandButton_ct__Fie:
	j	__23tPMenuItemCommandButtonUi17tPMenuCommandType
	nop

	.globl	tPMenuItemCommandButton_dt__FPvi
tPMenuItemCommandButton_dt__FPvi:
	j	_._23tPMenuItemCommandButton
	nop

	.globl	tPMenuItemGoToMenuButton_ct__Fie
tPMenuItemGoToMenuButton_ct__Fie:
	j	__24tPMenuItemGoToMenuButtonUiP6tPMenuPFR13tPMenuCommand_v
	nop

	.globl	tPMenuItemGoToMenuButton_dt__FPvi
tPMenuItemGoToMenuButton_dt__FPvi:
	j	_._24tPMenuItemGoToMenuButton
	nop

	.globl	tPMenuItemLeftRightChoice_ct__Fie
tPMenuItemLeftRightChoice_ct__Fie:
	j	__25tPMenuItemLeftRightChoiceUiP14tPListIterator
	nop

	.globl	tPMenuItemLeftRightChoice_dt__FPvi
tPMenuItemLeftRightChoice_dt__FPvi:
	j	_._25tPMenuItemLeftRightChoice
	nop

	.globl	tPMenuItemLeftRightSliderIndexed_ct__Fie
tPMenuItemLeftRightSliderIndexed_ct__Fie:
	j	__32tPMenuItemLeftRightSliderIndexedUiPicPc
	nop

	.globl	tPMenuItemLeftRightSliderIndexed_dt__FPvi
tPMenuItemLeftRightSliderIndexed_dt__FPvi:
	j	_._32tPMenuItemLeftRightSliderIndexed
	nop

	.globl	tPMenuItemLeftRightSlider_ct__Fie
tPMenuItemLeftRightSlider_ct__Fie:
	j	__25tPMenuItemLeftRightSliderUiPic
	nop

	.globl	tPMenuItemLeftRightSlider_dt__FPvi
tPMenuItemLeftRightSlider_dt__FPvi:
	j	_._25tPMenuItemLeftRightSlider
	nop

	.globl	tPMenuItemNonInteractiveText_ct__Fie
tPMenuItemNonInteractiveText_ct__Fie:
	j	__28tPMenuItemNonInteractiveTextUi
	nop

	.globl	tPMenuItemNonInteractiveText_dt__FPvi
tPMenuItemNonInteractiveText_dt__FPvi:
	j	_._28tPMenuItemNonInteractiveText
	nop

	.globl	tPMenu_ct__Fie
tPMenu_ct__Fie:
	j	__6tPMenuP10tPMenuIteme
	nop

	.globl	tPMenu_dt__FPvi
tPMenu_dt__FPvi:
	j	_._6tPMenu
	nop

	.globl	tScreenAudio_ctor__Fe
tScreenAudio_ctor__Fe:
	j	__12tScreenAudio
	nop

	.globl	tScreenCarSelect_ctor__Fe
tScreenCarSelect_ctor__Fe:
	j	tScreenCarSelect_ctor__FP16tScreenCarSelect
	nop

	.globl	tScreenCarSelect_dtor__Fe
tScreenCarSelect_dtor__Fe:
	j	tScreenCarSelect_dtor__FP16tScreenCarSelect
	nop

	.globl	tScreenControllerConfig_ctor__Fe
tScreenControllerConfig_ctor__Fe:
	j	__23tScreenControllerConfig
	nop

	.globl	tScreenMemcard_ctor__Fe
tScreenMemcard_ctor__Fe:
	j	__14tScreenMemcard
	nop

	.globl	tScreenTournSelect_ctor__Fe
tScreenTournSelect_ctor__Fe:
	j	__18tScreenTournSelect
	nop

	.globl	tScreenTournSelect_dtor__Fe
tScreenTournSelect_dtor__Fe:
	j	_._18tScreenTournSelect
	nop

	.globl	tScreenTournamentStandings_ctor__Fe
tScreenTournamentStandings_ctor__Fe:
	j	__26tScreenTournamentStandings
	nop

	.globl	tScreenTrophyRoom_ctor__Fe
tScreenTrophyRoom_ctor__Fe:
	j	__17tScreenTrophyRoom
	nop

	.globl	tScreenTrophyRoom_dtor__Fe
tScreenTrophyRoom_dtor__Fe:
	j	_._17tScreenTrophyRoom
	nop

	.globl	tScreen_ProcessInput__FP7tScreen7tPlayerR13tInputKeyTypeR12tMenuCommand
tScreen_ProcessInput__FP7tScreen7tPlayerR13tInputKeyTypeR12tMenuCommand:
	j	ProcessInput__7tScreen7tPlayerR13tInputKeyTypeR12tMenuCommand
	nop

	.globl	tScreen_ctor__Fe
tScreen_ctor__Fe:
	j	tScreen_ctor__FP7tScreen
	nop

	.globl	tScreen_dtor__Fe
tScreen_dtor__Fe:
	j	tScreen_dtor__FP7tScreen
	nop

	.globl	tUserNameMenuItem_ctor__Fe
tUserNameMenuItem_ctor__Fe:
	j	__17tUserNameMenuItemUi
	nop

	.globl	textpixels__Fe
textpixels__Fe:
	j	textpixels__FPc
	nop

	.globl	unpack
unpack:
	j	unpack__FPvT0
	nop

	.globl	unpacksize
unpacksize:
	j	unpacksize__FPv
	nop

	.globl	unpackz
unpackz:
	j	unpackz__FPvT0
	nop

